/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HospitalAdminRole;

import business.Business;
import business.Enterprise;
import business.Network;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.PrescriptionRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Panel for hospital admin to submit prescription requests to pharmacy
 * 
 * @author Maxwell Sowell
 * @author Akira Hanada
 */
public class SubmitPrescriptionJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Business business;


    public SubmitPrescriptionJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
        
        initComponents();
        populateComboBox();
        populateTable();
    }
    
    private void populateComboBox() {
        cmbMedication.removeAllItems();
        String[] medications = {"Penicillin", "Gabapentin", "Hydrocodone", "Alprazolam", "Atorvastatin", 
                               "Lisinopril", "Metformin", "Amlodipine", "Omeprazole", "Albuterol"};
        for (String med : medications) {
            cmbMedication.addItem(med);
        }
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPrescriptions.getModel();
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof PrescriptionRequest && request.getSender() != null 
                    && request.getSender().equals(userAccount)) {
                PrescriptionRequest rxRequest = (PrescriptionRequest) request;
                
                Object[] row = new Object[7];
                row[0] = sdf.format(rxRequest.getRequestDate());
                row[1] = rxRequest.getPatientName() != null ? rxRequest.getPatientName() : "Unknown";
                row[2] = rxRequest.getMedicationName() != null ? rxRequest.getMedicationName() : "N/A";
                row[3] = rxRequest.getDosage() != null ? rxRequest.getDosage() : "N/A";
                row[4] = rxRequest.getQuantity() > 0 ? rxRequest.getQuantity() + " pills" : "-";
                row[5] = rxRequest.getStatus() != null ? rxRequest.getStatus() : "Pending";
                row[6] = rxRequest.getFulfillmentNotes() != null ? rxRequest.getFulfillmentNotes() : "-";

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedication = new javax.swing.JLabel();
        lblDosage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrescriptions = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        txtPatientName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        cmbMedication = new javax.swing.JComboBox<>();
        txtDosage = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();

        lblMedication.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMedication.setText("Medication:");

        lblDosage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDosage.setText("Dosage:");

        tblPrescriptions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Patient", "Medication", "Dosage", "Quantity", "Status", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPrescriptions);

        btnSubmit.setText("Submit New Request");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle1.setText("New Prescription Request:");

        lblPatientName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPatientName.setText("Patient Name:");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("My Prescription Requests");

        cmbMedication.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penicillin", "Gabapentin", "Hydrocodone", "Alprazolam", "Atorvastatin" }));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantity.setText("Quantity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle1)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(lblDosage)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblQuantity))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblPatientName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMedication)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(176, 176, 176)
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedication)
                    .addComponent(cmbMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDosage)
                    .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            String patientName = txtPatientName.getText().trim();
            if (patientName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter patient name");
                return;
            }

            String medication = (String) cmbMedication.getSelectedItem();
            if (medication == null) {
                JOptionPane.showMessageDialog(this, "Please select medication");
                return;
            }
            
            String dosage = txtDosage.getText().trim();
            if (dosage.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter dosage");
                return;
            }
            
            String quantityStr = txtQuantity.getText().trim();
            if (quantityStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter quantity");
                return;
            }
            
            int quantity;
            try {
                quantity = Integer.parseInt(quantityStr);
                if (quantity <= 0) {
                    JOptionPane.showMessageDialog(this, "Quantity must be greater than 0");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter a valid quantity number");
                return;
            }

            // Find pharmacy organization
            Organization pharmacyOrg = null;
            for (Network network : business.getEcoSystem().getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseList()) {
                    if (enterprise.getName().contains("Healthcare") || enterprise.getName().contains("Provider")) {
                        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (org.getName().contains("Pharmacy")) {
                                pharmacyOrg = org;
                                break;
                            }
                        }
                        if (pharmacyOrg != null) break;
                    }
                }
                if (pharmacyOrg != null) break;
            }

            if (pharmacyOrg == null || pharmacyOrg.getUserAccountDirectory().getUserAccountList().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pharmacy organization not found");
                return;
            }

            // Create prescription request
            PrescriptionRequest rxRequest = new PrescriptionRequest();
            rxRequest.setPatientName(patientName);
            rxRequest.setMedicationName(medication);
            rxRequest.setDosage(dosage);
            rxRequest.setQuantity(quantity);
            rxRequest.setPrescribingDoctor(userAccount.getEmployee().getName());
            rxRequest.setMessage("Prescription for " + medication + " - " + dosage + " - Qty: " + quantity);
            rxRequest.setSender(userAccount);
            rxRequest.setReceiver(pharmacyOrg.getUserAccountDirectory().getUserAccountList().get(0));
            rxRequest.setStatus("Pending");

            // Add to both queues
            organization.getWorkQueue().getWorkRequestList().add(rxRequest);
            pharmacyOrg.getWorkQueue().getWorkRequestList().add(rxRequest);

            JOptionPane.showMessageDialog(this, 
                "Prescription request submitted successfully!\n\n" +
                "Patient: " + patientName + "\n" +
                "Medication: " + medication + "\n" +
                "Dosage: " + dosage + "\n" +
                "Quantity: " + quantity);

            // Clear form
            txtPatientName.setText("");
            cmbMedication.setSelectedIndex(0);
            txtDosage.setText("");
            txtQuantity.setText("");
            populateTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error submitting request: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        populateTable();

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbMedication;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDosage;
    private javax.swing.JLabel lblMedication;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblPrescriptions;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
