/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PharmacistRole;

import business.Business;
import business.Organization.PharmacyOrganization;
import business.UserAccount.UserAccount;
import business.WorkQueue.PrescriptionRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Work area for Pharmacists to process prescription requests
 * 
 * @author Maxwell Sowell
 */
public class PharmacistWorkAreaJPanel extends javax.swing.JPanel {
    
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private PharmacyOrganization organization;
    private Business business;
    

    public PharmacistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PharmacyOrganization organization, Business business) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
        
        initComponents();
        
        // Update panel title with logged-in pharmacist name
        lblTitle.setText("Pharmacist Work Area - " + account.getEmployee().getName());
        
        populateRequestTable();
    }

    
    private void populateRequestTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblWorkRequests.getModel();
            model.setRowCount(0);

            // Get prescription requests assigned to this pharmacist
            for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
                if (request instanceof PrescriptionRequest && request.getReceiver() != null && request.getReceiver().equals(userAccount)) {
                    PrescriptionRequest rxRequest = (PrescriptionRequest) request;

                    Object[] row = new Object[8];
                    row[0] = rxRequest.getPatientName() != null ? rxRequest.getPatientName() : "Unknown";
                    row[1] = rxRequest.getMedicationName() != null ? rxRequest.getMedicationName() : "N/A";
                    row[2] = rxRequest.getDosage() != null ? rxRequest.getDosage() : "N/A";
                    row[3] = rxRequest.getQuantity();
                    row[4] = rxRequest.getPrescribingDoctor() != null ? rxRequest.getPrescribingDoctor() : "N/A";
                    row[5] = rxRequest.getStatus() != null ? rxRequest.getStatus() : "Pending";
                    row[6] = rxRequest.getFulfillmentNotes() != null ? rxRequest.getFulfillmentNotes() : "-";
                    row[7] = rxRequest.getRequestDate();

                    model.addRow(row);
                    
                }
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error loading prescriptions: " + e.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequests = new javax.swing.JTable();
        btnFulfillPrescription = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFulfillmentNotes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        tblWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient", "Medication", "Dosage", "Quantity", "Doctor", "Status", "Notes", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequests);

        btnFulfillPrescription.setText("Fullfill Prescription");
        btnFulfillPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFulfillPrescriptionActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Pharmacist Work Area - <Name>");

        txtFulfillmentNotes.setColumns(20);
        txtFulfillmentNotes.setRows(5);
        jScrollPane2.setViewportView(txtFulfillmentNotes);

        jLabel1.setText("Fulfillment Notes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnFulfillPrescription)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblTitle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefresh))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFulfillPrescription)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFulfillPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFulfillPrescriptionActionPerformed
        
        int selectedRow = tblWorkRequests.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this,"Select a prescription to fulfill");
            return;
        }
        
        String notes = txtFulfillmentNotes.getText().trim();
        if (notes.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Enter fulfillment notes before processing");
            return;
        }
        
        
        DefaultTableModel model = (DefaultTableModel) tblWorkRequests.getModel();
        String patientName = (String) model.getValueAt(selectedRow, 0);
        PrescriptionRequest selectedRequest = null;
        
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof PrescriptionRequest) {
                PrescriptionRequest rxReq = (PrescriptionRequest) request;
                if (rxReq.getPatientName().equals(patientName) && rxReq.getReceiver().equals(userAccount)) {
                    selectedRequest = rxReq;
                    break;
                }
            }
        }
        
        
        if (selectedRequest != null) {
            selectedRequest.setStatus("Fulfilled");
            selectedRequest.setFulfillmentNotes(notes);
            selectedRequest.setResolveDate(new java.util.Date());
            
            JOptionPane.showMessageDialog(this,"Prescription fulfilled");
            
            
            txtFulfillmentNotes.setText("");
            populateRequestTable();
            
        } else {
            JOptionPane.showMessageDialog(this, "Request not found in system");
        }
        
    }//GEN-LAST:event_btnFulfillPrescriptionActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFulfillPrescription;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblWorkRequests;
    private javax.swing.JTextArea txtFulfillmentNotes;
    // End of variables declaration//GEN-END:variables
}
