/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VaccineStorageSpecialistRole;

import business.Business;
import business.Domain.Vaccine;
import business.Enterprise;
import business.Network;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.ColdChainFailureRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Creates Work Area for Vaccine Storage Specialist
 * 
 * @author Maxwell Sowell
 */
public class VaccineStorageSpecialistWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Business business;


    public VaccineStorageSpecialistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
        
        initComponents();
        
        
        lblTitle.setText("Vaccine Storage Specialist Work Area - " + account.getEmployee().getName());

        populateVaccineInventory();
        populateReports();
        
    }
    
    
    private void populateVaccineInventory() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
            model.setRowCount(0);

            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");

            for (Vaccine vaccine : business.getVaccineDirectory()) {
                Object[] row = new Object[5];
                row[0] = vaccine.getName();
                row[1] = vaccine.getManufacturer();
                row[2] = 1000; // TODO given more time-- track stored vaccine inventory
                row[3] = vaccine.getExpirationDate() != null ? sdf.format(vaccine.getExpirationDate()) : "N/A";
                row[4] = vaccine.getStorageTemperature() != null ? vaccine.getStorageTemperature() : "N/A";

                model.addRow(row);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading inventory: " + e.getMessage());
        }
    }
    
    
    private void populateReports() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblReports.getModel();
            model.setRowCount(0);

            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");

            // This specialist's failure reports
            for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
                if (request instanceof ColdChainFailureRequest && request.getSender() != null && request.getSender().equals(userAccount)) {
                    ColdChainFailureRequest ccRequest = (ColdChainFailureRequest) request;

                    Object[] row = new Object[6];
                    row[0] = sdf.format(ccRequest.getRequestDate());
                    row[1] = ccRequest.getAffectedVaccine() != null ? ccRequest.getAffectedVaccine().getName() : "N/A";
                    row[2] = ccRequest.getAffectedQuantity();
                    row[3] = ccRequest.getFailureType() != null ? ccRequest.getFailureType() : "N/A";
                    row[4] = ccRequest.getStatus() != null ? ccRequest.getStatus() : "Pending";
                    row[5] = ccRequest.getReplacementStatus() != null ? ccRequest.getReplacementStatus() : "Pending";

                    model.addRow(row);
                    
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading reports: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        btnReport = new javax.swing.JButton();

        jLabel1.setText("My Cold Chain Failure Reports:");

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaccine", "Manufacturer", "Quantity", "Expiration Date", "Storage Temp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventory);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Vaccine Storage Specialist Work Area - <Name>");

        jLabel2.setText("Vaccine Inventory:");

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Report Date", "Vaccine", "Affected Qty", "Failure Type", "Report Status", "Replacement Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReports);

        btnReport.setText("Report Cold Chain Failure");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblTitle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRefresh))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        
        populateVaccineInventory();
        populateReports();
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        
        // Get failure details
        String[] failureTypes = {"Temperature Excursion", "Equipment Malfunction", "Power Failure", "Human Error"};
        String failureType = (String) JOptionPane.showInputDialog(
                this, "Select failure type:","Report Cold Chain Failure",
                JOptionPane.QUESTION_MESSAGE,null,failureTypes,failureTypes[0]);
        if (failureType == null) return;
        
        
        // Select vaccine if any exist
        if (business.getVaccineDirectory().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No vaccines in system", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Vaccine[] vaccines = business.getVaccineDirectory().toArray(new Vaccine[0]);
        Vaccine affectedVaccine = (Vaccine) JOptionPane.showInputDialog(
                this, "Select affected vaccine:","Report Cold Chain Failure",
                JOptionPane.QUESTION_MESSAGE, null,vaccines,vaccines[0]);
        if (affectedVaccine == null) return;
        
        
        // Get affected quantity
        String qtyStr = JOptionPane.showInputDialog(this, "Enter affected quantity:", "0");
        if (qtyStr == null) return;
        
        int affectedQty;
        try {
            affectedQty = Integer.parseInt(qtyStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        String tempRange = JOptionPane.showInputDialog(this, "Temperature range during failure:", "10-15°C");
        String duration = JOptionPane.showInputDialog(this, "Duration of exposure:", "2 hours");
        String action = JOptionPane.showInputDialog(this, "Corrective action taken:", "Vaccines quarantined, awaiting disposal guidance");
        
        
        // Find state Provider Coordinator to send report to
        Organization stateProviderRegistry = null;
        for (Network network : business.getEcoSystem().getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseList()) {
                if (enterprise.getName().contains("State Health")) {
                    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (org.getName().contains("Provider Registry")) {
                            stateProviderRegistry = org;
                            break;
                        }
                    }
                }
                if (stateProviderRegistry != null) break;
            }
            if (stateProviderRegistry != null) break;
        }
        
        if (stateProviderRegistry == null || stateProviderRegistry.getUserAccountDirectory().getUserAccountList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "State Provider Registry not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        // Create the cold chain failure request
        ColdChainFailureRequest ccRequest = new ColdChainFailureRequest();
        ccRequest.setAffectedVaccine(affectedVaccine);
        ccRequest.setAffectedQuantity(affectedQty);
        ccRequest.setFailureType(failureType);
        ccRequest.setTemperatureRange(tempRange != null ? tempRange : "N/A");
        ccRequest.setDurationOfExposure(duration != null ? duration : "N/A");
        ccRequest.setCorrectiveAction(action != null ? action : "N/A");
        ccRequest.setSender(userAccount);
        ccRequest.setReceiver(stateProviderRegistry.getUserAccountDirectory().getUserAccountList().get(0)); // Just picking the first for our purposes
        ccRequest.setMessage("Cold Chain Failure: " + affectedVaccine.getName() + " - Qty: " + affectedQty);
        ccRequest.setStatus("Pending Review");
        
        
        // Add to work queue
        organization.getWorkQueue().getWorkRequestList().add(ccRequest);
        stateProviderRegistry.getWorkQueue().getWorkRequestList().add(ccRequest);
        
        JOptionPane.showMessageDialog(this,
                "Cold chain failure successfully reported.\n\n" +
                "Vaccine: " + affectedVaccine.getName() + "\n" +
                "Quantity: " + affectedQty + "\n" +
                "Type: " + failureType + "\n\n" +
                "State Provider Coordinator notified!",
                "Report Submitted",JOptionPane.INFORMATION_MESSAGE);
        
        
        // Finally refresh table
        populateReports();
        
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblReports;
    // End of variables declaration//GEN-END:variables
}
