/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProviderCoordinatorRole;

import business.Business;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.ColdChainFailureRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Panel for provider coordinator to respond to vaccine cold chain failure reports
 * 
 * @author Maxwell Sowell
 */
public class ProcessColdChainFailureRequestsJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Business business;


    public ProcessColdChainFailureRequestsJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
        
        initComponents();
        populateRequestTable();
        
    }

    
    private void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblReports.getModel();
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof ColdChainFailureRequest) {
                ColdChainFailureRequest ccRequest = (ColdChainFailureRequest) request;
                String facility = ccRequest.getSender() != null ? 
                    ccRequest.getSender().getEmployee().getName() : "Unknown";
                
                Object[] row = new Object[7];
                row[0] = sdf.format(ccRequest.getRequestDate());
                row[1] = ccRequest.getAffectedVaccine() != null ? ccRequest.getAffectedVaccine().getName() : "N/A";
                row[2] = ccRequest.getAffectedQuantity();
                row[3] = ccRequest.getFailureType() != null ? ccRequest.getFailureType() : "N/A";
                row[4] = facility;
                row[5] = ccRequest.getStatus() != null ? ccRequest.getStatus() : "Pending";
                row[6] = ccRequest.getReplacementStatus() != null ? ccRequest.getReplacementStatus() : "Pending";

                
                model.addRow(row);
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Vaccine", "Affected Qty", "Failure Type", "Facility", "Report Status", "Replacement Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReports);

        btnProcess.setText("Process Report");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Process Cold Chain Failure Reports");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(353, 353, 353)
                        .addComponent(btnRefresh))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProcess)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnProcess))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed

        int selectedRow = tblReports.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a report");
            return;
        }
        
        
        // Get the cold chain request object
        ColdChainFailureRequest selectedRequest = null;
        int currentRow = 0;
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof ColdChainFailureRequest) {
                if (currentRow == selectedRow) {
                    selectedRequest = (ColdChainFailureRequest) request;
                    break;
                }
                currentRow++;
            }
        }
        
        if (selectedRequest == null) {
            JOptionPane.showMessageDialog(this, "Request not found");
            return;
        }
        
        
        // Update ReportStatus
        String[] reportStatuses = {"Pending","Approved", "Denied", "Investigation Needed"}; // TODO build investigation workflow
        String newReportStatus = (String) JOptionPane.showInputDialog(
                this,"Update report status:", "Update Report Status",
                JOptionPane.QUESTION_MESSAGE,null,reportStatuses,reportStatuses[0]);
        
        if (newReportStatus == null) return;
        
        
        // Update ReplacementStatus
        String[] replacementStatuses = {"Not Ordered", "Ordered from CDC", "In Transit", "Delivered", "More Info Needed"}; // TODO also integrate this panel with the coordinator interacting with the CDC about replacement protocol
        String newReplacementStatus = (String) JOptionPane.showInputDialog(
                this,"Update replacement status:","Update Replacement Status",
                JOptionPane.QUESTION_MESSAGE,null,replacementStatuses,replacementStatuses[0]);
            
        if (newReplacementStatus == null) return;
        
      
        selectedRequest.setStatus(newReportStatus);
        selectedRequest.setReplacementStatus(newReplacementStatus);
        selectedRequest.setResolveDate(new java.util.Date());
        
        
        DefaultTableModel model = (DefaultTableModel) tblReports.getModel();
        model.setValueAt(newReportStatus, selectedRow, 5);
        model.setValueAt(newReplacementStatus, selectedRow, 6);

        
        JOptionPane.showMessageDialog(this,"Cold chain failure report addressed. Storage specialist notified.");
        
        populateRequestTable();


    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblReports;
    // End of variables declaration//GEN-END:variables
}
