/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ClinicManagerRole;

import business.Business;
import business.Enterprise;
import business.Network;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.LabTestRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Panel for clinic manager to request a test from lab services
 * 
 * Please note that the RequestLabTestJPanel under ui.DoctorRole is old legacy code
 * (along with DoctorWorkAreaJPanel) and so should not be considered part of this workflow
 * 
 * @author Maxwell Sowell
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Business business;
    
    
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
        
        initComponents();
        populateTable();
        
    }
    
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblLabRequests.getModel();
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof LabTestRequest && request.getSender() != null 
                    && request.getSender().equals(userAccount)) {
                LabTestRequest labRequest = (LabTestRequest) request;
                
                Object[] row = new Object[5];
                row[0] = sdf.format(labRequest.getRequestDate());
                row[1] = labRequest.getPatientName() != null ? labRequest.getPatientName() : "Unknown";
                row[2] = labRequest.getTestType() != null ? labRequest.getTestType() : "N/A";
                row[3] = labRequest.getStatus() != null ? labRequest.getStatus() : "Pending";
                row[4] = labRequest.getTestResult() != null ? labRequest.getTestResult() : "-";
                
                model.addRow(row);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        cmbTestType = new javax.swing.JComboBox<>();
        lblResult1 = new javax.swing.JLabel();
        lblResult2 = new javax.swing.JLabel();
        cmbUrgency = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLabRequests = new javax.swing.JTable();
        lblTitle1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        btnSubmit.setText("Submit New Request");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblPatientName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPatientName.setText("Patient Name:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("My Lab Test Requests");

        cmbTestType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COVID-19 PCR Test", "COVID-19 Antibody Test", "Influenza Test", "Blood Culture", "Complete Blood Count" }));

        lblResult1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResult1.setText("Test Type:");

        lblResult2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResult2.setText("Urgency:");

        cmbUrgency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "URGENT" }));

        tblLabRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Patient", "Test Type", "Status", "Results"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLabRequests);

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle1.setText("New Lab Test Request:");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(135, 135, 135)
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPatientName)
                                            .addComponent(lblResult1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblResult2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmbTestType, javax.swing.GroupLayout.Alignment.LEADING, 0, 270, Short.MAX_VALUE)
                                            .addComponent(txtPatientName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbUrgency, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(96, 96, 96)
                                        .addComponent(btnSubmit)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResult1)
                    .addComponent(cmbTestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUrgency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResult2))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            String patientName = txtPatientName.getText().trim();
            if (patientName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter patient name");
                return;
            }

            String testType = (String) cmbTestType.getSelectedItem();
            String urgency = (String) cmbUrgency.getSelectedItem();


            // Get lab org recipient
            Organization labOrg = null;
            for (Network network : business.getEcoSystem().getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseList()) {
                    if (enterprise.getName().contains("Healthcare") || enterprise.getName().contains("Provider")) {
                        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (org.getName().contains("Laboratory") || org.getName().contains("Lab")) {
                                labOrg = org;
                                break;
                            }
                        }
                    }
                    if (labOrg != null) break;
                }
                if (labOrg != null) break;
            }

            if (labOrg == null || labOrg.getUserAccountDirectory().getUserAccountList().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lab organization not found");
                return;      
            }


            // Create the request
            LabTestRequest labRequest = new LabTestRequest();
            labRequest.setPatientName(patientName);
            labRequest.setTestType(testType);
            labRequest.setUrgencyLevel(urgency);
            labRequest.setMessage("Patient: " + patientName + " - " + testType);
            labRequest.setSender(userAccount);
            labRequest.setReceiver(labOrg.getUserAccountDirectory().getUserAccountList().get(0));
            labRequest.setStatus("Pending");

            organization.getWorkQueue().getWorkRequestList().add(labRequest);
            labOrg.getWorkQueue().getWorkRequestList().add(labRequest);

            JOptionPane.showMessageDialog(this, "Lab test request submitted");

            txtPatientName.setText("");
            cmbTestType.setSelectedIndex(0);
            cmbUrgency.setSelectedIndex(0);
            populateTable();
        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error submitting request: " + e.getMessage());
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        
        populateTable();
        
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbTestType;
    private javax.swing.JComboBox<String> cmbUrgency;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblResult1;
    private javax.swing.JLabel lblResult2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblLabRequests;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
